INSERT INTO EMPLOYEE(NAME,POSITION) VALUES('ALI','MANAGER');
INSERT INTO EMPLOYEE(NAME,POSITION) VALUES('JACK','DEVELOPER');
INSERT INTO EMPLOYEE(NAME,POSITION) VALUES('MA','DEVELOPER');
INSERT INTO EMPLOYEE(NAME,POSITION) VALUES('MA','TECHNICAL MANAGER');